### ISSUE TITLE
Compiler nontermination

### ISSUE THREAD

**Issue by dhil** [cmcl/frankjnr#3]
The following program causes the Frank compiler not terminate:
```haskell
data Bool = True | False

iffy : Bool -> {X} -> {X} -> X
iffy True t _  = t!
iffy False _ f = f!

main : Unit
main! = iffy True {1} {2}
```
... well, I don't know whether it eventually terminates. After 1 minute I gave up.

**Comment by cmcl** [comment]
The above program terminates as of commit f4268967. A regression test (r3.fk) has been added to the test suite.
