### ISSUE TITLE
Type checking error when pattern matching against data types that contain computations

### ISSUE THREAD

**Issue by slindley** [cmcl/frankjnr#5]
The following fails to type check:

    data Maybe X = just X | nothing
    
    foo : Maybe {Unit} -> Unit
    foo (just x) = x!

with the error:

     application:expected suspended computation, got: MkFTVar "X$f0"

It looks like `x` is being given a flexible type inside the body of `foo` when it should be given type `{Unit}`.

**Comment by slindley** [comment]
This is easy to work around. The following does type check!

    force : {X} -> X
    force x = x!
    
    foo : Maybe {Unit} -> Unit
    foo (just x) = force x

**Comment by cmcl** [comment]
Resolved (cbddce33) and regression test added (r5.fk) using the above example.
